// This file has been automatically generated by capnp-es.
import * as $ from "capnp-es";
export const _capnpFileId = 0x910b52243f5e98f9n;
export const KeyKind = {
    /**
* the key typed, when it goes down and each time it repeats
*
*/
    PRESS: 0,
    /**
* the key went down or repeats, just before its press
*
*/
    DOWN: 1,
    /**
* the key came up
*
*/
    UP: 2
} as const;
export type KeyKind = (typeof KeyKind)[keyof typeof KeyKind];
export class Modifiers extends $.Struct {
    static readonly _capnp = {
        displayName: "Modifiers",
        id: "c21a4ef1c265e37a",
        size: new $.ObjectSize(8, 0),
    };
    get alt(): boolean {
        return $.utils.getBit(0, this);
    }
    set alt(value: boolean) {
        $.utils.setBit(0, value, this);
    }
    get ctrl(): boolean {
        return $.utils.getBit(1, this);
    }
    set ctrl(value: boolean) {
        $.utils.setBit(1, value, this);
    }
    /**
* The Windows, Command or Super key.
*
*/
    get shift(): boolean {
        return $.utils.getBit(2, this);
    }
    set shift(value: boolean) {
        $.utils.setBit(2, value, this);
    }
    get meta(): boolean {
        return $.utils.getBit(3, this);
    }
    set meta(value: boolean) {
        $.utils.setBit(3, value, this);
    }
    toString(): string { return "Modifiers_" + super.toString(); }
}
export class KeyEvent extends $.Struct {
    static readonly _capnp = {
        displayName: "KeyEvent",
        id: "c131f14137902b5c",
        size: new $.ObjectSize(8, 2),
    };
    /**
* The W3C KeyboardEvent.key value, such as "ArrowLeft", "a" or " ".
*
*/
    get kind(): KeyKind {
        return $.utils.getUint16(0, this) as KeyKind;
    }
    set kind(value: KeyKind) {
        $.utils.setUint16(0, value, this);
    }
    get key(): string {
        return $.utils.getText(0, this);
    }
    set key(value: string) {
        $.utils.setText(0, value, this);
    }
    _adoptModifiers(value: $.Orphan<Modifiers>): void {
        $.utils.adopt(value, $.utils.getPointer(1, this));
    }
    _disownModifiers(): $.Orphan<Modifiers> {
        return $.utils.disown(this.modifiers);
    }
    get modifiers(): Modifiers {
        return $.utils.getStruct(1, Modifiers, this);
    }
    _hasModifiers(): boolean {
        return !$.utils.isNull($.utils.getPointer(1, this));
    }
    _initModifiers(): Modifiers {
        return $.utils.initStructAt(1, Modifiers, this);
    }
    set modifiers(value: Modifiers) {
        $.utils.copyFrom(value, $.utils.getPointer(1, this));
    }
    toString(): string { return "KeyEvent_" + super.toString(); }
}
export const MouseButton = {
    LEFT: 0,
    MIDDLE: 1,
    RIGHT: 2,
    BACK: 3,
    FORWARD: 4
} as const;
export type MouseButton = (typeof MouseButton)[keyof typeof MouseButton];
/**
* The pointer left the surface, and x and y hold its last position.
*
*/
export class MouseEvent_Wheel extends $.Struct {
    static readonly _capnp = {
        displayName: "wheel",
        id: "97f79e6f32d770e9",
        size: new $.ObjectSize(24, 1),
    };
    get dx(): number {
        return $.utils.getFloat32(12, this);
    }
    set dx(value: number) {
        $.utils.setFloat32(12, value, this);
    }
    get dy(): number {
        return $.utils.getFloat32(16, this);
    }
    set dy(value: number) {
        $.utils.setFloat32(16, value, this);
    }
    toString(): string { return "MouseEvent_Wheel_" + super.toString(); }
}
export const MouseEvent_Which = {
    MOVE: 0,
    DOWN: 1,
    /**
* In notches of the wheel. As in W3C, dx > 0 scrolls right and
* dy > 0 scrolls down.
*
*/
    UP: 2,
    /**
* The pointer left the surface, and x and y hold its last position.
*
*/
    WHEEL: 3,
    LEAVE: 4
} as const;
export type MouseEvent_Which = (typeof MouseEvent_Which)[keyof typeof MouseEvent_Which];
export class MouseEvent extends $.Struct {
    static readonly MOVE = MouseEvent_Which.MOVE;
    static readonly DOWN = MouseEvent_Which.DOWN;
    static readonly UP = MouseEvent_Which.UP;
    static readonly WHEEL = MouseEvent_Which.WHEEL;
    static readonly LEAVE = MouseEvent_Which.LEAVE;
    static readonly _capnp = {
        displayName: "MouseEvent",
        id: "b050e1005b4185e4",
        size: new $.ObjectSize(24, 1),
    };
    get x(): number {
        return $.utils.getFloat32(0, this);
    }
    set x(value: number) {
        $.utils.setFloat32(0, value, this);
    }
    get y(): number {
        return $.utils.getFloat32(4, this);
    }
    set y(value: number) {
        $.utils.setFloat32(4, value, this);
    }
    _adoptModifiers(value: $.Orphan<Modifiers>): void {
        $.utils.adopt(value, $.utils.getPointer(0, this));
    }
    _disownModifiers(): $.Orphan<Modifiers> {
        return $.utils.disown(this.modifiers);
    }
    /**
* The buttons held after this event, one bit (1 << MouseButton) each.
*
*/
    get modifiers(): Modifiers {
        return $.utils.getStruct(0, Modifiers, this);
    }
    _hasModifiers(): boolean {
        return !$.utils.isNull($.utils.getPointer(0, this));
    }
    _initModifiers(): Modifiers {
        return $.utils.initStructAt(0, Modifiers, this);
    }
    set modifiers(value: Modifiers) {
        $.utils.copyFrom(value, $.utils.getPointer(0, this));
    }
    get buttons(): number {
        return $.utils.getUint8(8, this);
    }
    set buttons(value: number) {
        $.utils.setUint8(8, value, this);
    }
    get _isMove(): boolean {
        return $.utils.getUint16(10, this) === 0;
    }
    set move(_: true) {
        $.utils.setUint16(10, 0, this);
    }
    get down(): MouseButton {
        $.utils.testWhich("down", $.utils.getUint16(10, this), 1, this);
        return $.utils.getUint16(12, this) as MouseButton;
    }
    get _isDown(): boolean {
        return $.utils.getUint16(10, this) === 1;
    }
    set down(value: MouseButton) {
        $.utils.setUint16(10, 1, this);
        $.utils.setUint16(12, value, this);
    }
    /**
* In notches of the wheel. As in W3C, dx > 0 scrolls right and
* dy > 0 scrolls down.
*
*/
    get up(): MouseButton {
        $.utils.testWhich("up", $.utils.getUint16(10, this), 2, this);
        return $.utils.getUint16(12, this) as MouseButton;
    }
    get _isUp(): boolean {
        return $.utils.getUint16(10, this) === 2;
    }
    set up(value: MouseButton) {
        $.utils.setUint16(10, 2, this);
        $.utils.setUint16(12, value, this);
    }
    /**
* The pointer left the surface, and x and y hold its last position.
*
*/
    get wheel(): MouseEvent_Wheel {
        $.utils.testWhich("wheel", $.utils.getUint16(10, this), 3, this);
        return $.utils.getAs(MouseEvent_Wheel, this);
    }
    _initWheel(): MouseEvent_Wheel {
        $.utils.setUint16(10, 3, this);
        return $.utils.getAs(MouseEvent_Wheel, this);
    }
    get _isWheel(): boolean {
        return $.utils.getUint16(10, this) === 3;
    }
    set wheel(_: true) {
        $.utils.setUint16(10, 3, this);
    }
    get _isLeave(): boolean {
        return $.utils.getUint16(10, this) === 4;
    }
    set leave(_: true) {
        $.utils.setUint16(10, 4, this);
    }
    toString(): string { return "MouseEvent_" + super.toString(); }
    which(): MouseEvent_Which {
        return $.utils.getUint16(10, this) as MouseEvent_Which;
    }
}
export class ResizeEvent extends $.Struct {
    static readonly _capnp = {
        displayName: "ResizeEvent",
        id: "f7e6fe36692f1146",
        size: new $.ObjectSize(8, 0),
    };
    get width(): number {
        return $.utils.getFloat32(0, this);
    }
    set width(value: number) {
        $.utils.setFloat32(0, value, this);
    }
    get height(): number {
        return $.utils.getFloat32(4, this);
    }
    set height(value: number) {
        $.utils.setFloat32(4, value, this);
    }
    toString(): string { return "ResizeEvent_" + super.toString(); }
}
export const PadButton = {
    DPAD_UP: 0,
    DPAD_DOWN: 1,
    DPAD_LEFT: 2,
    DPAD_RIGHT: 3,
    A: 4,
    B: 5,
    X: 6,
    Y: 7,
    LEFT_SHOULDER: 8,
    RIGHT_SHOULDER: 9,
    SELECT: 10,
    START: 11
} as const;
export type PadButton = (typeof PadButton)[keyof typeof PadButton];
export const PadEvent_Which = {
    DOWN: 0,
    /**
* The view found a pad, which sends the buttons from now on.
*
*/
    UP: 1,
    /**
* The view lost its pad.
*
*/
    CONNECTED: 2,
    DISCONNECTED: 3
} as const;
export type PadEvent_Which = (typeof PadEvent_Which)[keyof typeof PadEvent_Which];
export class PadEvent extends $.Struct {
    static readonly DOWN = PadEvent_Which.DOWN;
    static readonly UP = PadEvent_Which.UP;
    static readonly CONNECTED = PadEvent_Which.CONNECTED;
    static readonly DISCONNECTED = PadEvent_Which.DISCONNECTED;
    static readonly _capnp = {
        displayName: "PadEvent",
        id: "b007d78b502d468c",
        size: new $.ObjectSize(8, 0),
    };
    get down(): PadButton {
        $.utils.testWhich("down", $.utils.getUint16(2, this), 0, this);
        return $.utils.getUint16(0, this) as PadButton;
    }
    get _isDown(): boolean {
        return $.utils.getUint16(2, this) === 0;
    }
    set down(value: PadButton) {
        $.utils.setUint16(2, 0, this);
        $.utils.setUint16(0, value, this);
    }
    /**
* The view found a pad, which sends the buttons from now on.
*
*/
    get up(): PadButton {
        $.utils.testWhich("up", $.utils.getUint16(2, this), 1, this);
        return $.utils.getUint16(0, this) as PadButton;
    }
    get _isUp(): boolean {
        return $.utils.getUint16(2, this) === 1;
    }
    set up(value: PadButton) {
        $.utils.setUint16(2, 1, this);
        $.utils.setUint16(0, value, this);
    }
    get _isConnected(): boolean {
        return $.utils.getUint16(2, this) === 2;
    }
    set connected(_: true) {
        $.utils.setUint16(2, 2, this);
    }
    get _isDisconnected(): boolean {
        return $.utils.getUint16(2, this) === 3;
    }
    set disconnected(_: true) {
        $.utils.setUint16(2, 3, this);
    }
    toString(): string { return "PadEvent_" + super.toString(); }
    which(): PadEvent_Which {
        return $.utils.getUint16(2, this) as PadEvent_Which;
    }
}
export const InputEvent_Which = {
    KEY: 0,
    MOUSE: 1,
    RESIZE: 2,
    PAD: 3
} as const;
export type InputEvent_Which = (typeof InputEvent_Which)[keyof typeof InputEvent_Which];
export class InputEvent extends $.Struct {
    static readonly KEY = InputEvent_Which.KEY;
    static readonly MOUSE = InputEvent_Which.MOUSE;
    static readonly RESIZE = InputEvent_Which.RESIZE;
    static readonly PAD = InputEvent_Which.PAD;
    static readonly _capnp = {
        displayName: "InputEvent",
        id: "ba2e1947e44159b3",
        size: new $.ObjectSize(8, 1),
    };
    _adoptKey(value: $.Orphan<KeyEvent>): void {
        $.utils.setUint16(0, 0, this);
        $.utils.adopt(value, $.utils.getPointer(0, this));
    }
    _disownKey(): $.Orphan<KeyEvent> {
        return $.utils.disown(this.key);
    }
    get key(): KeyEvent {
        $.utils.testWhich("key", $.utils.getUint16(0, this), 0, this);
        return $.utils.getStruct(0, KeyEvent, this);
    }
    _hasKey(): boolean {
        return !$.utils.isNull($.utils.getPointer(0, this));
    }
    _initKey(): KeyEvent {
        $.utils.setUint16(0, 0, this);
        return $.utils.initStructAt(0, KeyEvent, this);
    }
    get _isKey(): boolean {
        return $.utils.getUint16(0, this) === 0;
    }
    set key(value: KeyEvent) {
        $.utils.setUint16(0, 0, this);
        $.utils.copyFrom(value, $.utils.getPointer(0, this));
    }
    _adoptMouse(value: $.Orphan<MouseEvent>): void {
        $.utils.setUint16(0, 1, this);
        $.utils.adopt(value, $.utils.getPointer(0, this));
    }
    _disownMouse(): $.Orphan<MouseEvent> {
        return $.utils.disown(this.mouse);
    }
    get mouse(): MouseEvent {
        $.utils.testWhich("mouse", $.utils.getUint16(0, this), 1, this);
        return $.utils.getStruct(0, MouseEvent, this);
    }
    _hasMouse(): boolean {
        return !$.utils.isNull($.utils.getPointer(0, this));
    }
    _initMouse(): MouseEvent {
        $.utils.setUint16(0, 1, this);
        return $.utils.initStructAt(0, MouseEvent, this);
    }
    get _isMouse(): boolean {
        return $.utils.getUint16(0, this) === 1;
    }
    set mouse(value: MouseEvent) {
        $.utils.setUint16(0, 1, this);
        $.utils.copyFrom(value, $.utils.getPointer(0, this));
    }
    _adoptResize(value: $.Orphan<ResizeEvent>): void {
        $.utils.setUint16(0, 2, this);
        $.utils.adopt(value, $.utils.getPointer(0, this));
    }
    _disownResize(): $.Orphan<ResizeEvent> {
        return $.utils.disown(this.resize);
    }
    get resize(): ResizeEvent {
        $.utils.testWhich("resize", $.utils.getUint16(0, this), 2, this);
        return $.utils.getStruct(0, ResizeEvent, this);
    }
    _hasResize(): boolean {
        return !$.utils.isNull($.utils.getPointer(0, this));
    }
    _initResize(): ResizeEvent {
        $.utils.setUint16(0, 2, this);
        return $.utils.initStructAt(0, ResizeEvent, this);
    }
    get _isResize(): boolean {
        return $.utils.getUint16(0, this) === 2;
    }
    set resize(value: ResizeEvent) {
        $.utils.setUint16(0, 2, this);
        $.utils.copyFrom(value, $.utils.getPointer(0, this));
    }
    _adoptPad(value: $.Orphan<PadEvent>): void {
        $.utils.setUint16(0, 3, this);
        $.utils.adopt(value, $.utils.getPointer(0, this));
    }
    _disownPad(): $.Orphan<PadEvent> {
        return $.utils.disown(this.pad);
    }
    get pad(): PadEvent {
        $.utils.testWhich("pad", $.utils.getUint16(0, this), 3, this);
        return $.utils.getStruct(0, PadEvent, this);
    }
    _hasPad(): boolean {
        return !$.utils.isNull($.utils.getPointer(0, this));
    }
    _initPad(): PadEvent {
        $.utils.setUint16(0, 3, this);
        return $.utils.initStructAt(0, PadEvent, this);
    }
    get _isPad(): boolean {
        return $.utils.getUint16(0, this) === 3;
    }
    set pad(value: PadEvent) {
        $.utils.setUint16(0, 3, this);
        $.utils.copyFrom(value, $.utils.getPointer(0, this));
    }
    toString(): string { return "InputEvent_" + super.toString(); }
    which(): InputEvent_Which {
        return $.utils.getUint16(0, this) as InputEvent_Which;
    }
}
