// This file has been automatically generated by capnp-es.
import * as $ from "capnp-es";
import { InputEvent, KeyEvent, KeyKind, Modifiers, MouseButton, MouseEvent, PadButton, PadEvent, ResizeEvent } from "./event.ts";
export const _capnpFileId = 0x9f762cd052af55c1n;
export class Asset extends $.Struct {
    static readonly _capnp = {
        displayName: "Asset",
        id: "88f3a977523d4769",
        size: new $.ObjectSize(8, 1),
    };
    get id(): number {
        return $.utils.getUint32(0, this);
    }
    set id(value: number) {
        $.utils.setUint32(0, value, this);
    }
    _adoptBlob(value: $.Orphan<$.Data>): void {
        $.utils.adopt(value, $.utils.getPointer(0, this));
    }
    _disownBlob(): $.Orphan<$.Data> {
        return $.utils.disown(this.blob);
    }
    get blob(): $.Data {
        return $.utils.getData(0, this);
    }
    _hasBlob(): boolean {
        return !$.utils.isNull($.utils.getPointer(0, this));
    }
    _initBlob(length: number): $.Data {
        return $.utils.initData(0, length, this);
    }
    set blob(value: $.Data) {
        $.utils.copyFrom(value, $.utils.getPointer(0, this));
    }
    toString(): string { return "Asset_" + super.toString(); }
}
/**
* The player that the frame goes to, from 1, or 0 for every player.
*
*/
export class Frame extends $.Struct {
    static readonly _capnp = {
        displayName: "Frame",
        id: "e991d773b31d238a",
        size: new $.ObjectSize(8, 1),
    };
    /**
* A whole message whose root is the Scene of scene.capnp. The server
* copies the bytes into the frame of a ServerToView with no decode.
*
*/
    get player(): number {
        return $.utils.getUint32(0, this);
    }
    set player(value: number) {
        $.utils.setUint32(0, value, this);
    }
    _adoptScene(value: $.Orphan<$.Data>): void {
        $.utils.adopt(value, $.utils.getPointer(0, this));
    }
    _disownScene(): $.Orphan<$.Data> {
        return $.utils.disown(this.scene);
    }
    get scene(): $.Data {
        return $.utils.getData(0, this);
    }
    _hasScene(): boolean {
        return !$.utils.isNull($.utils.getPointer(0, this));
    }
    _initScene(length: number): $.Data {
        return $.utils.initData(0, length, this);
    }
    set scene(value: $.Data) {
        $.utils.copyFrom(value, $.utils.getPointer(0, this));
    }
    toString(): string { return "Frame_" + super.toString(); }
}
export class Hello extends $.Struct {
    static readonly _capnp = {
        displayName: "Hello",
        id: "e7d12ca45395eb04",
        size: new $.ObjectSize(8, 0),
    };
    get minPlayers(): number {
        return $.utils.getUint32(0, this);
    }
    set minPlayers(value: number) {
        $.utils.setUint32(0, value, this);
    }
    get maxPlayers(): number {
        return $.utils.getUint32(4, this);
    }
    set maxPlayers(value: number) {
        $.utils.setUint32(4, value, this);
    }
    toString(): string { return "Hello_" + super.toString(); }
}
export const EngineToServer_Which = {
    /**
* One per repaint.
*
*/
    ASSET: 0,
    /**
* To the server, as the engine reads a tick. The server sends the
* next tick only after it, so the ticks of an engine slower than
* the timer do not pile up.
*
*/
    FRAME: 1,
    TICK_TAKEN: 2
} as const;
export type EngineToServer_Which = (typeof EngineToServer_Which)[keyof typeof EngineToServer_Which];
export class EngineToServer extends $.Struct {
    static readonly ASSET = EngineToServer_Which.ASSET;
    static readonly FRAME = EngineToServer_Which.FRAME;
    static readonly TICK_TAKEN = EngineToServer_Which.TICK_TAKEN;
    static readonly _capnp = {
        displayName: "EngineToServer",
        id: "b1c8572799f538c6",
        size: new $.ObjectSize(8, 1),
    };
    _adoptAsset(value: $.Orphan<Asset>): void {
        $.utils.setUint16(0, 0, this);
        $.utils.adopt(value, $.utils.getPointer(0, this));
    }
    _disownAsset(): $.Orphan<Asset> {
        return $.utils.disown(this.asset);
    }
    /**
* One per repaint.
*
*/
    get asset(): Asset {
        $.utils.testWhich("asset", $.utils.getUint16(0, this), 0, this);
        return $.utils.getStruct(0, Asset, this);
    }
    _hasAsset(): boolean {
        return !$.utils.isNull($.utils.getPointer(0, this));
    }
    _initAsset(): Asset {
        $.utils.setUint16(0, 0, this);
        return $.utils.initStructAt(0, Asset, this);
    }
    get _isAsset(): boolean {
        return $.utils.getUint16(0, this) === 0;
    }
    set asset(value: Asset) {
        $.utils.setUint16(0, 0, this);
        $.utils.copyFrom(value, $.utils.getPointer(0, this));
    }
    _adoptFrame(value: $.Orphan<Frame>): void {
        $.utils.setUint16(0, 1, this);
        $.utils.adopt(value, $.utils.getPointer(0, this));
    }
    _disownFrame(): $.Orphan<Frame> {
        return $.utils.disown(this.frame);
    }
    /**
* To the server, as the engine reads a tick. The server sends the
* next tick only after it, so the ticks of an engine slower than
* the timer do not pile up.
*
*/
    get frame(): Frame {
        $.utils.testWhich("frame", $.utils.getUint16(0, this), 1, this);
        return $.utils.getStruct(0, Frame, this);
    }
    _hasFrame(): boolean {
        return !$.utils.isNull($.utils.getPointer(0, this));
    }
    _initFrame(): Frame {
        $.utils.setUint16(0, 1, this);
        return $.utils.initStructAt(0, Frame, this);
    }
    get _isFrame(): boolean {
        return $.utils.getUint16(0, this) === 1;
    }
    set frame(value: Frame) {
        $.utils.setUint16(0, 1, this);
        $.utils.copyFrom(value, $.utils.getPointer(0, this));
    }
    get _isTickTaken(): boolean {
        return $.utils.getUint16(0, this) === 2;
    }
    set tickTaken(_: true) {
        $.utils.setUint16(0, 2, this);
    }
    toString(): string { return "EngineToServer_" + super.toString(); }
    which(): EngineToServer_Which {
        return $.utils.getUint16(0, this) as EngineToServer_Which;
    }
}
export class ViewToServer extends $.Struct {
    static readonly _capnp = {
        displayName: "ViewToServer",
        id: "8eb07b55c452da3f",
        size: new $.ObjectSize(0, 1),
    };
    _adoptEvent(value: $.Orphan<InputEvent>): void {
        $.utils.adopt(value, $.utils.getPointer(0, this));
    }
    _disownEvent(): $.Orphan<InputEvent> {
        return $.utils.disown(this.event);
    }
    get event(): InputEvent {
        return $.utils.getStruct(0, InputEvent, this);
    }
    _hasEvent(): boolean {
        return !$.utils.isNull($.utils.getPointer(0, this));
    }
    _initEvent(): InputEvent {
        return $.utils.initStructAt(0, InputEvent, this);
    }
    set event(value: InputEvent) {
        $.utils.copyFrom(value, $.utils.getPointer(0, this));
    }
    toString(): string { return "ViewToServer_" + super.toString(); }
}
export class Member extends $.Struct {
    static readonly _capnp = {
        displayName: "Member",
        id: "f35218b88ea1ff57",
        size: new $.ObjectSize(0, 1),
    };
    get nickname(): string {
        return $.utils.getText(0, this);
    }
    set nickname(value: string) {
        $.utils.setText(0, value, this);
    }
    toString(): string { return "Member_" + super.toString(); }
}
export class Start extends $.Struct {
    static readonly _capnp = {
        displayName: "Start",
        id: "f5a707fb1e20309f",
        size: new $.ObjectSize(0, 1),
    };
    static _Members: $.ListCtor<Member>;
    _adoptMembers(value: $.Orphan<$.List<Member>>): void {
        $.utils.adopt(value, $.utils.getPointer(0, this));
    }
    _disownMembers(): $.Orphan<$.List<Member>> {
        return $.utils.disown(this.members);
    }
    get members(): $.List<Member> {
        return $.utils.getList(0, Start._Members, this);
    }
    _hasMembers(): boolean {
        return !$.utils.isNull($.utils.getPointer(0, this));
    }
    _initMembers(length: number): $.List<Member> {
        return $.utils.initList(0, Start._Members, length, this);
    }
    set members(value: $.List<Member>) {
        $.utils.copyFrom(value, $.utils.getPointer(0, this));
    }
    toString(): string { return "Start_" + super.toString(); }
}
/**
* The player, from 1.
*
*/
export class PlayerInput extends $.Struct {
    static readonly _capnp = {
        displayName: "PlayerInput",
        id: "c159bfa766a70a95",
        size: new $.ObjectSize(8, 1),
    };
    get player(): number {
        return $.utils.getUint32(0, this);
    }
    set player(value: number) {
        $.utils.setUint32(0, value, this);
    }
    _adoptEvent(value: $.Orphan<InputEvent>): void {
        $.utils.adopt(value, $.utils.getPointer(0, this));
    }
    _disownEvent(): $.Orphan<InputEvent> {
        return $.utils.disown(this.event);
    }
    get event(): InputEvent {
        return $.utils.getStruct(0, InputEvent, this);
    }
    _hasEvent(): boolean {
        return !$.utils.isNull($.utils.getPointer(0, this));
    }
    _initEvent(): InputEvent {
        return $.utils.initStructAt(0, InputEvent, this);
    }
    set event(value: InputEvent) {
        $.utils.copyFrom(value, $.utils.getPointer(0, this));
    }
    toString(): string { return "PlayerInput_" + super.toString(); }
}
export class Tick extends $.Struct {
    static readonly _capnp = {
        displayName: "Tick",
        id: "8515ddeaf6d82317",
        size: new $.ObjectSize(0, 0),
    };
    toString(): string { return "Tick_" + super.toString(); }
}
export const ServerToEngine_Which = {
    /**
* Time for the engine to draw the next frames.
*
*/
    INPUT: 0,
    /**
* The server dropped the asset of this id, to keep the room under
* its limits. The engine sends the image again, under a new id,
* before a frame that draws it.
*
*/
    TICK: 1,
    LOST: 2
} as const;
export type ServerToEngine_Which = (typeof ServerToEngine_Which)[keyof typeof ServerToEngine_Which];
export class ServerToEngine extends $.Struct {
    static readonly INPUT = ServerToEngine_Which.INPUT;
    static readonly TICK = ServerToEngine_Which.TICK;
    static readonly LOST = ServerToEngine_Which.LOST;
    static readonly _capnp = {
        displayName: "ServerToEngine",
        id: "c0901718457727f5",
        size: new $.ObjectSize(8, 1),
    };
    _adoptInput(value: $.Orphan<PlayerInput>): void {
        $.utils.setUint16(0, 0, this);
        $.utils.adopt(value, $.utils.getPointer(0, this));
    }
    _disownInput(): $.Orphan<PlayerInput> {
        return $.utils.disown(this.input);
    }
    /**
* Time for the engine to draw the next frames.
*
*/
    get input(): PlayerInput {
        $.utils.testWhich("input", $.utils.getUint16(0, this), 0, this);
        return $.utils.getStruct(0, PlayerInput, this);
    }
    _hasInput(): boolean {
        return !$.utils.isNull($.utils.getPointer(0, this));
    }
    _initInput(): PlayerInput {
        $.utils.setUint16(0, 0, this);
        return $.utils.initStructAt(0, PlayerInput, this);
    }
    get _isInput(): boolean {
        return $.utils.getUint16(0, this) === 0;
    }
    set input(value: PlayerInput) {
        $.utils.setUint16(0, 0, this);
        $.utils.copyFrom(value, $.utils.getPointer(0, this));
    }
    _adoptTick(value: $.Orphan<Tick>): void {
        $.utils.setUint16(0, 1, this);
        $.utils.adopt(value, $.utils.getPointer(0, this));
    }
    _disownTick(): $.Orphan<Tick> {
        return $.utils.disown(this.tick);
    }
    /**
* The server dropped the asset of this id, to keep the room under
* its limits. The engine sends the image again, under a new id,
* before a frame that draws it.
*
*/
    get tick(): Tick {
        $.utils.testWhich("tick", $.utils.getUint16(0, this), 1, this);
        return $.utils.getStruct(0, Tick, this);
    }
    _hasTick(): boolean {
        return !$.utils.isNull($.utils.getPointer(0, this));
    }
    _initTick(): Tick {
        $.utils.setUint16(0, 1, this);
        return $.utils.initStructAt(0, Tick, this);
    }
    get _isTick(): boolean {
        return $.utils.getUint16(0, this) === 1;
    }
    set tick(value: Tick) {
        $.utils.setUint16(0, 1, this);
        $.utils.copyFrom(value, $.utils.getPointer(0, this));
    }
    get lost(): number {
        $.utils.testWhich("lost", $.utils.getUint16(0, this), 2, this);
        return $.utils.getUint32(4, this);
    }
    get _isLost(): boolean {
        return $.utils.getUint16(0, this) === 2;
    }
    set lost(value: number) {
        $.utils.setUint16(0, 2, this);
        $.utils.setUint32(4, value, this);
    }
    toString(): string { return "ServerToEngine_" + super.toString(); }
    which(): ServerToEngine_Which {
        return $.utils.getUint16(0, this) as ServerToEngine_Which;
    }
}
export const ServerToView_Which = {
    /**
* A whole message whose root is the Scene of scene.capnp, as the
* frame of the engine holds it.
*
*/
    ASSET: 0,
    /**
* The view drops the asset of this id, since no frame of the view
* draws it.
*
*/
    FRAME: 1,
    FORGET: 2
} as const;
export type ServerToView_Which = (typeof ServerToView_Which)[keyof typeof ServerToView_Which];
export class ServerToView extends $.Struct {
    static readonly ASSET = ServerToView_Which.ASSET;
    static readonly FRAME = ServerToView_Which.FRAME;
    static readonly FORGET = ServerToView_Which.FORGET;
    static readonly _capnp = {
        displayName: "ServerToView",
        id: "fdef3aa297411099",
        size: new $.ObjectSize(8, 1),
    };
    _adoptAsset(value: $.Orphan<Asset>): void {
        $.utils.setUint16(0, 0, this);
        $.utils.adopt(value, $.utils.getPointer(0, this));
    }
    _disownAsset(): $.Orphan<Asset> {
        return $.utils.disown(this.asset);
    }
    /**
* A whole message whose root is the Scene of scene.capnp, as the
* frame of the engine holds it.
*
*/
    get asset(): Asset {
        $.utils.testWhich("asset", $.utils.getUint16(0, this), 0, this);
        return $.utils.getStruct(0, Asset, this);
    }
    _hasAsset(): boolean {
        return !$.utils.isNull($.utils.getPointer(0, this));
    }
    _initAsset(): Asset {
        $.utils.setUint16(0, 0, this);
        return $.utils.initStructAt(0, Asset, this);
    }
    get _isAsset(): boolean {
        return $.utils.getUint16(0, this) === 0;
    }
    set asset(value: Asset) {
        $.utils.setUint16(0, 0, this);
        $.utils.copyFrom(value, $.utils.getPointer(0, this));
    }
    _adoptFrame(value: $.Orphan<$.Data>): void {
        $.utils.setUint16(0, 1, this);
        $.utils.adopt(value, $.utils.getPointer(0, this));
    }
    _disownFrame(): $.Orphan<$.Data> {
        return $.utils.disown(this.frame);
    }
    /**
* The view drops the asset of this id, since no frame of the view
* draws it.
*
*/
    get frame(): $.Data {
        $.utils.testWhich("frame", $.utils.getUint16(0, this), 1, this);
        return $.utils.getData(0, this);
    }
    _hasFrame(): boolean {
        return !$.utils.isNull($.utils.getPointer(0, this));
    }
    _initFrame(length: number): $.Data {
        $.utils.setUint16(0, 1, this);
        return $.utils.initData(0, length, this);
    }
    get _isFrame(): boolean {
        return $.utils.getUint16(0, this) === 1;
    }
    set frame(value: $.Data) {
        $.utils.setUint16(0, 1, this);
        $.utils.copyFrom(value, $.utils.getPointer(0, this));
    }
    get forget(): number {
        $.utils.testWhich("forget", $.utils.getUint16(0, this), 2, this);
        return $.utils.getUint32(4, this);
    }
    get _isForget(): boolean {
        return $.utils.getUint16(0, this) === 2;
    }
    set forget(value: number) {
        $.utils.setUint16(0, 2, this);
        $.utils.setUint32(4, value, this);
    }
    toString(): string { return "ServerToView_" + super.toString(); }
    which(): ServerToView_Which {
        return $.utils.getUint16(0, this) as ServerToView_Which;
    }
}
Start._Members = $.CompositeList(Member);
