// This file has been automatically generated by capnp-es.
import * as $ from "capnp-es";
export const _capnpFileId = 0xe6fe272699b1f2b7n;
export class Rgba extends $.Struct {
    static readonly _capnp = {
        displayName: "Rgba",
        id: "cf2020f3dae30afc",
        size: new $.ObjectSize(8, 0),
    };
    get r(): number {
        return $.utils.getUint8(0, this);
    }
    set r(value: number) {
        $.utils.setUint8(0, value, this);
    }
    get g(): number {
        return $.utils.getUint8(1, this);
    }
    set g(value: number) {
        $.utils.setUint8(1, value, this);
    }
    get b(): number {
        return $.utils.getUint8(2, this);
    }
    set b(value: number) {
        $.utils.setUint8(2, value, this);
    }
    get a(): number {
        return $.utils.getUint8(3, this);
    }
    set a(value: number) {
        $.utils.setUint8(3, value, this);
    }
    toString(): string { return "Rgba_" + super.toString(); }
}
export const LineCap = {
    BUTT: 0,
    ROUND: 1,
    SQUARE: 2
} as const;
export type LineCap = (typeof LineCap)[keyof typeof LineCap];
export const LineJoin = {
    MITER: 0,
    ROUND: 1,
    BEVEL: 2
} as const;
export type LineJoin = (typeof LineJoin)[keyof typeof LineJoin];
export const FillRule = {
    NON_ZERO: 0,
    EVEN_ODD: 1
} as const;
export type FillRule = (typeof FillRule)[keyof typeof FillRule];
export const FontStyle = {
    NORMAL: 0,
    ITALIC: 1,
    OBLIQUE: 2
} as const;
export type FontStyle = (typeof FontStyle)[keyof typeof FontStyle];
export class Stop extends $.Struct {
    static readonly _capnp = {
        displayName: "Stop",
        id: "b14b6ddb2711c32b",
        size: new $.ObjectSize(8, 1),
    };
    get offset(): number {
        return $.utils.getFloat32(0, this);
    }
    set offset(value: number) {
        $.utils.setFloat32(0, value, this);
    }
    _adoptColor(value: $.Orphan<Rgba>): void {
        $.utils.adopt(value, $.utils.getPointer(0, this));
    }
    _disownColor(): $.Orphan<Rgba> {
        return $.utils.disown(this.color);
    }
    get color(): Rgba {
        return $.utils.getStruct(0, Rgba, this);
    }
    _hasColor(): boolean {
        return !$.utils.isNull($.utils.getPointer(0, this));
    }
    _initColor(): Rgba {
        return $.utils.initStructAt(0, Rgba, this);
    }
    set color(value: Rgba) {
        $.utils.copyFrom(value, $.utils.getPointer(0, this));
    }
    toString(): string { return "Stop_" + super.toString(); }
}
export const SpreadMode = {
    PAD: 0,
    REFLECT: 1,
    REPEAT: 2
} as const;
export type SpreadMode = (typeof SpreadMode)[keyof typeof SpreadMode];
export class LinearGradient extends $.Struct {
    static readonly _capnp = {
        displayName: "LinearGradient",
        id: "e37627eb46f926ee",
        size: new $.ObjectSize(24, 1),
    };
    static _Stops: $.ListCtor<Stop>;
    get x0(): number {
        return $.utils.getFloat32(0, this);
    }
    set x0(value: number) {
        $.utils.setFloat32(0, value, this);
    }
    get y0(): number {
        return $.utils.getFloat32(4, this);
    }
    set y0(value: number) {
        $.utils.setFloat32(4, value, this);
    }
    get x1(): number {
        return $.utils.getFloat32(8, this);
    }
    set x1(value: number) {
        $.utils.setFloat32(8, value, this);
    }
    get y1(): number {
        return $.utils.getFloat32(12, this);
    }
    set y1(value: number) {
        $.utils.setFloat32(12, value, this);
    }
    _adoptStops(value: $.Orphan<$.List<Stop>>): void {
        $.utils.adopt(value, $.utils.getPointer(0, this));
    }
    _disownStops(): $.Orphan<$.List<Stop>> {
        return $.utils.disown(this.stops);
    }
    get stops(): $.List<Stop> {
        return $.utils.getList(0, LinearGradient._Stops, this);
    }
    _hasStops(): boolean {
        return !$.utils.isNull($.utils.getPointer(0, this));
    }
    _initStops(length: number): $.List<Stop> {
        return $.utils.initList(0, LinearGradient._Stops, length, this);
    }
    set stops(value: $.List<Stop>) {
        $.utils.copyFrom(value, $.utils.getPointer(0, this));
    }
    get spread(): SpreadMode {
        return $.utils.getUint16(16, this) as SpreadMode;
    }
    set spread(value: SpreadMode) {
        $.utils.setUint16(16, value, this);
    }
    toString(): string { return "LinearGradient_" + super.toString(); }
}
export class RadialGradient extends $.Struct {
    static readonly _capnp = {
        displayName: "RadialGradient",
        id: "d6aa06d3b287dbe1",
        size: new $.ObjectSize(16, 1),
    };
    static _Stops: $.ListCtor<Stop>;
    get cx(): number {
        return $.utils.getFloat32(0, this);
    }
    set cx(value: number) {
        $.utils.setFloat32(0, value, this);
    }
    get cy(): number {
        return $.utils.getFloat32(4, this);
    }
    set cy(value: number) {
        $.utils.setFloat32(4, value, this);
    }
    get radius(): number {
        return $.utils.getFloat32(8, this);
    }
    set radius(value: number) {
        $.utils.setFloat32(8, value, this);
    }
    _adoptStops(value: $.Orphan<$.List<Stop>>): void {
        $.utils.adopt(value, $.utils.getPointer(0, this));
    }
    _disownStops(): $.Orphan<$.List<Stop>> {
        return $.utils.disown(this.stops);
    }
    get stops(): $.List<Stop> {
        return $.utils.getList(0, RadialGradient._Stops, this);
    }
    _hasStops(): boolean {
        return !$.utils.isNull($.utils.getPointer(0, this));
    }
    _initStops(length: number): $.List<Stop> {
        return $.utils.initList(0, RadialGradient._Stops, length, this);
    }
    set stops(value: $.List<Stop>) {
        $.utils.copyFrom(value, $.utils.getPointer(0, this));
    }
    get spread(): SpreadMode {
        return $.utils.getUint16(12, this) as SpreadMode;
    }
    set spread(value: SpreadMode) {
        $.utils.setUint16(12, value, this);
    }
    toString(): string { return "RadialGradient_" + super.toString(); }
}
export const Paint_Which = {
    SOLID: 0,
    LINEAR: 1,
    RADIAL: 2
} as const;
export type Paint_Which = (typeof Paint_Which)[keyof typeof Paint_Which];
export class Paint extends $.Struct {
    static readonly SOLID = Paint_Which.SOLID;
    static readonly LINEAR = Paint_Which.LINEAR;
    static readonly RADIAL = Paint_Which.RADIAL;
    static readonly _capnp = {
        displayName: "Paint",
        id: "81002fa0daf06ced",
        size: new $.ObjectSize(8, 1),
    };
    _adoptSolid(value: $.Orphan<Rgba>): void {
        $.utils.setUint16(0, 0, this);
        $.utils.adopt(value, $.utils.getPointer(0, this));
    }
    _disownSolid(): $.Orphan<Rgba> {
        return $.utils.disown(this.solid);
    }
    get solid(): Rgba {
        $.utils.testWhich("solid", $.utils.getUint16(0, this), 0, this);
        return $.utils.getStruct(0, Rgba, this);
    }
    _hasSolid(): boolean {
        return !$.utils.isNull($.utils.getPointer(0, this));
    }
    _initSolid(): Rgba {
        $.utils.setUint16(0, 0, this);
        return $.utils.initStructAt(0, Rgba, this);
    }
    get _isSolid(): boolean {
        return $.utils.getUint16(0, this) === 0;
    }
    set solid(value: Rgba) {
        $.utils.setUint16(0, 0, this);
        $.utils.copyFrom(value, $.utils.getPointer(0, this));
    }
    _adoptLinear(value: $.Orphan<LinearGradient>): void {
        $.utils.setUint16(0, 1, this);
        $.utils.adopt(value, $.utils.getPointer(0, this));
    }
    _disownLinear(): $.Orphan<LinearGradient> {
        return $.utils.disown(this.linear);
    }
    get linear(): LinearGradient {
        $.utils.testWhich("linear", $.utils.getUint16(0, this), 1, this);
        return $.utils.getStruct(0, LinearGradient, this);
    }
    _hasLinear(): boolean {
        return !$.utils.isNull($.utils.getPointer(0, this));
    }
    _initLinear(): LinearGradient {
        $.utils.setUint16(0, 1, this);
        return $.utils.initStructAt(0, LinearGradient, this);
    }
    get _isLinear(): boolean {
        return $.utils.getUint16(0, this) === 1;
    }
    set linear(value: LinearGradient) {
        $.utils.setUint16(0, 1, this);
        $.utils.copyFrom(value, $.utils.getPointer(0, this));
    }
    _adoptRadial(value: $.Orphan<RadialGradient>): void {
        $.utils.setUint16(0, 2, this);
        $.utils.adopt(value, $.utils.getPointer(0, this));
    }
    _disownRadial(): $.Orphan<RadialGradient> {
        return $.utils.disown(this.radial);
    }
    get radial(): RadialGradient {
        $.utils.testWhich("radial", $.utils.getUint16(0, this), 2, this);
        return $.utils.getStruct(0, RadialGradient, this);
    }
    _hasRadial(): boolean {
        return !$.utils.isNull($.utils.getPointer(0, this));
    }
    _initRadial(): RadialGradient {
        $.utils.setUint16(0, 2, this);
        return $.utils.initStructAt(0, RadialGradient, this);
    }
    get _isRadial(): boolean {
        return $.utils.getUint16(0, this) === 2;
    }
    set radial(value: RadialGradient) {
        $.utils.setUint16(0, 2, this);
        $.utils.copyFrom(value, $.utils.getPointer(0, this));
    }
    get fallback(): number {
        return $.utils.getUint32(4, this);
    }
    set fallback(value: number) {
        $.utils.setUint32(4, value, this);
    }
    get hasFallback(): boolean {
        return $.utils.getBit(16, this);
    }
    set hasFallback(value: boolean) {
        $.utils.setBit(16, value, this);
    }
    toString(): string { return "Paint_" + super.toString(); }
    which(): Paint_Which {
        return $.utils.getUint16(0, this) as Paint_Which;
    }
}
export class PathStyle extends $.Struct {
    static readonly _capnp = {
        displayName: "PathStyle",
        id: "ded9314dcbaf69f4",
        size: new $.ObjectSize(24, 3),
    };
    _adoptFill(value: $.Orphan<Paint>): void {
        $.utils.adopt(value, $.utils.getPointer(0, this));
    }
    _disownFill(): $.Orphan<Paint> {
        return $.utils.disown(this.fill);
    }
    get fill(): Paint {
        return $.utils.getStruct(0, Paint, this);
    }
    _hasFill(): boolean {
        return !$.utils.isNull($.utils.getPointer(0, this));
    }
    _initFill(): Paint {
        return $.utils.initStructAt(0, Paint, this);
    }
    set fill(value: Paint) {
        $.utils.copyFrom(value, $.utils.getPointer(0, this));
    }
    _adoptStroke(value: $.Orphan<Paint>): void {
        $.utils.adopt(value, $.utils.getPointer(1, this));
    }
    _disownStroke(): $.Orphan<Paint> {
        return $.utils.disown(this.stroke);
    }
    get stroke(): Paint {
        return $.utils.getStruct(1, Paint, this);
    }
    _hasStroke(): boolean {
        return !$.utils.isNull($.utils.getPointer(1, this));
    }
    _initStroke(): Paint {
        return $.utils.initStructAt(1, Paint, this);
    }
    set stroke(value: Paint) {
        $.utils.copyFrom(value, $.utils.getPointer(1, this));
    }
    get strokeWidth(): number {
        return $.utils.getFloat32(0, this);
    }
    set strokeWidth(value: number) {
        $.utils.setFloat32(0, value, this);
    }
    get lineCap(): LineCap {
        return $.utils.getUint16(4, this) as LineCap;
    }
    set lineCap(value: LineCap) {
        $.utils.setUint16(4, value, this);
    }
    get lineJoin(): LineJoin {
        return $.utils.getUint16(6, this) as LineJoin;
    }
    set lineJoin(value: LineJoin) {
        $.utils.setUint16(6, value, this);
    }
    /**
* Closes every sub-path, so the stroke joins at the start of each one.
*
*/
    get fillRule(): FillRule {
        return $.utils.getUint16(8, this) as FillRule;
    }
    set fillRule(value: FillRule) {
        $.utils.setUint16(8, value, this);
    }
    /**
* A miter limit below 1 is 1. The limit compares a ratio that is never
* below 1, so the two say the same thing, and SVG rejects a smaller one.
*
*/
    get closed(): boolean {
        return $.utils.getBit(80, this);
    }
    set closed(value: boolean) {
        $.utils.setBit(80, value, this);
    }
    /**
* Alternating on and off lengths. An odd list repeats to an even one.
* An empty list, a negative or non-finite length, lengths that sum to
* zero or a non-finite offset make the stroke solid.
*
*/
    get miterLimit(): number {
        return $.utils.getFloat32(12, this);
    }
    set miterLimit(value: number) {
        $.utils.setFloat32(12, value, this);
    }
    _adoptDashArray(value: $.Orphan<$.List<number>>): void {
        $.utils.adopt(value, $.utils.getPointer(2, this));
    }
    _disownDashArray(): $.Orphan<$.List<number>> {
        return $.utils.disown(this.dashArray);
    }
    get dashArray(): $.List<number> {
        return $.utils.getList(2, $.Float32List, this);
    }
    _hasDashArray(): boolean {
        return !$.utils.isNull($.utils.getPointer(2, this));
    }
    _initDashArray(length: number): $.List<number> {
        return $.utils.initList(2, $.Float32List, length, this);
    }
    set dashArray(value: $.List<number>) {
        $.utils.copyFrom(value, $.utils.getPointer(2, this));
    }
    get dashOffset(): number {
        return $.utils.getFloat32(16, this);
    }
    set dashOffset(value: number) {
        $.utils.setFloat32(16, value, this);
    }
    toString(): string { return "PathStyle_" + super.toString(); }
}
export class ClipPath extends $.Struct {
    static readonly _capnp = {
        displayName: "ClipPath",
        id: "e874d268a5368ff4",
        size: new $.ObjectSize(8, 2),
    };
    _adoptVerbs(value: $.Orphan<$.Data>): void {
        $.utils.adopt(value, $.utils.getPointer(0, this));
    }
    _disownVerbs(): $.Orphan<$.Data> {
        return $.utils.disown(this.verbs);
    }
    get verbs(): $.Data {
        return $.utils.getData(0, this);
    }
    _hasVerbs(): boolean {
        return !$.utils.isNull($.utils.getPointer(0, this));
    }
    _initVerbs(length: number): $.Data {
        return $.utils.initData(0, length, this);
    }
    set verbs(value: $.Data) {
        $.utils.copyFrom(value, $.utils.getPointer(0, this));
    }
    _adoptCoords(value: $.Orphan<$.List<number>>): void {
        $.utils.adopt(value, $.utils.getPointer(1, this));
    }
    _disownCoords(): $.Orphan<$.List<number>> {
        return $.utils.disown(this.coords);
    }
    get coords(): $.List<number> {
        return $.utils.getList(1, $.Float32List, this);
    }
    _hasCoords(): boolean {
        return !$.utils.isNull($.utils.getPointer(1, this));
    }
    _initCoords(length: number): $.List<number> {
        return $.utils.initList(1, $.Float32List, length, this);
    }
    set coords(value: $.List<number>) {
        $.utils.copyFrom(value, $.utils.getPointer(1, this));
    }
    get fillRule(): FillRule {
        return $.utils.getUint16(0, this) as FillRule;
    }
    set fillRule(value: FillRule) {
        $.utils.setUint16(0, value, this);
    }
    toString(): string { return "ClipPath_" + super.toString(); }
}
export class Bitmap extends $.Struct {
    static readonly _capnp = {
        displayName: "Bitmap",
        id: "ba050e57ad278304",
        size: new $.ObjectSize(32, 0),
    };
    get id(): number {
        return $.utils.getUint32(0, this);
    }
    set id(value: number) {
        $.utils.setUint32(0, value, this);
    }
    get m0(): number {
        return $.utils.getFloat32(4, this);
    }
    set m0(value: number) {
        $.utils.setFloat32(4, value, this);
    }
    get m1(): number {
        return $.utils.getFloat32(8, this);
    }
    set m1(value: number) {
        $.utils.setFloat32(8, value, this);
    }
    get m2(): number {
        return $.utils.getFloat32(12, this);
    }
    set m2(value: number) {
        $.utils.setFloat32(12, value, this);
    }
    get m3(): number {
        return $.utils.getFloat32(16, this);
    }
    set m3(value: number) {
        $.utils.setFloat32(16, value, this);
    }
    get m4(): number {
        return $.utils.getFloat32(20, this);
    }
    set m4(value: number) {
        $.utils.setFloat32(20, value, this);
    }
    /**
* A hint, so a reader draws a sampling it does not know as smooth.
*
*/
    get m5(): number {
        return $.utils.getFloat32(24, this);
    }
    set m5(value: number) {
        $.utils.setFloat32(24, value, this);
    }
    get sampling(): Sampling {
        return $.utils.getUint16(28, this) as Sampling;
    }
    set sampling(value: Sampling) {
        $.utils.setUint16(28, value, this);
    }
    toString(): string { return "Bitmap_" + super.toString(); }
}
export const Sampling = {
    SMOOTH: 0,
    NEAREST: 1
} as const;
export type Sampling = (typeof Sampling)[keyof typeof Sampling];
export class TextNode extends $.Struct {
    static readonly _capnp = {
        displayName: "TextNode",
        id: "d125d1c5d6466788",
        size: new $.ObjectSize(40, 4),
    };
    _adoptFill(value: $.Orphan<Paint>): void {
        $.utils.adopt(value, $.utils.getPointer(0, this));
    }
    _disownFill(): $.Orphan<Paint> {
        return $.utils.disown(this.fill);
    }
    get fill(): Paint {
        return $.utils.getStruct(0, Paint, this);
    }
    _hasFill(): boolean {
        return !$.utils.isNull($.utils.getPointer(0, this));
    }
    _initFill(): Paint {
        return $.utils.initStructAt(0, Paint, this);
    }
    set fill(value: Paint) {
        $.utils.copyFrom(value, $.utils.getPointer(0, this));
    }
    _adoptStroke(value: $.Orphan<Paint>): void {
        $.utils.adopt(value, $.utils.getPointer(1, this));
    }
    _disownStroke(): $.Orphan<Paint> {
        return $.utils.disown(this.stroke);
    }
    get stroke(): Paint {
        return $.utils.getStruct(1, Paint, this);
    }
    _hasStroke(): boolean {
        return !$.utils.isNull($.utils.getPointer(1, this));
    }
    _initStroke(): Paint {
        return $.utils.initStructAt(1, Paint, this);
    }
    set stroke(value: Paint) {
        $.utils.copyFrom(value, $.utils.getPointer(1, this));
    }
    get strokeWidth(): number {
        return $.utils.getFloat32(0, this);
    }
    set strokeWidth(value: number) {
        $.utils.setFloat32(0, value, this);
    }
    get m0(): number {
        return $.utils.getFloat32(4, this);
    }
    set m0(value: number) {
        $.utils.setFloat32(4, value, this);
    }
    get m1(): number {
        return $.utils.getFloat32(8, this);
    }
    set m1(value: number) {
        $.utils.setFloat32(8, value, this);
    }
    get m2(): number {
        return $.utils.getFloat32(12, this);
    }
    set m2(value: number) {
        $.utils.setFloat32(12, value, this);
    }
    get m3(): number {
        return $.utils.getFloat32(16, this);
    }
    set m3(value: number) {
        $.utils.setFloat32(16, value, this);
    }
    get m4(): number {
        return $.utils.getFloat32(20, this);
    }
    set m4(value: number) {
        $.utils.setFloat32(20, value, this);
    }
    get m5(): number {
        return $.utils.getFloat32(24, this);
    }
    set m5(value: number) {
        $.utils.setFloat32(24, value, this);
    }
    get size(): number {
        return $.utils.getFloat32(28, this);
    }
    set size(value: number) {
        $.utils.setFloat32(28, value, this);
    }
    get family(): string {
        return $.utils.getText(2, this);
    }
    set family(value: string) {
        $.utils.setText(2, value, this);
    }
    get weight(): number {
        return $.utils.getUint16(32, this);
    }
    set weight(value: number) {
        $.utils.setUint16(32, value, this);
    }
    get style(): FontStyle {
        return $.utils.getUint16(34, this) as FontStyle;
    }
    set style(value: FontStyle) {
        $.utils.setUint16(34, value, this);
    }
    get underline(): boolean {
        return $.utils.getBit(288, this);
    }
    set underline(value: boolean) {
        $.utils.setBit(288, value, this);
    }
    get text(): string {
        return $.utils.getText(3, this);
    }
    set text(value: string) {
        $.utils.setText(3, value, this);
    }
    toString(): string { return "TextNode_" + super.toString(); }
}
export class Path extends $.Struct {
    static readonly _capnp = {
        displayName: "Path",
        id: "a7d6de6bc8e46887",
        size: new $.ObjectSize(0, 3),
    };
    _adoptStyle(value: $.Orphan<PathStyle>): void {
        $.utils.adopt(value, $.utils.getPointer(0, this));
    }
    _disownStyle(): $.Orphan<PathStyle> {
        return $.utils.disown(this.style);
    }
    get style(): PathStyle {
        return $.utils.getStruct(0, PathStyle, this);
    }
    _hasStyle(): boolean {
        return !$.utils.isNull($.utils.getPointer(0, this));
    }
    _initStyle(): PathStyle {
        return $.utils.initStructAt(0, PathStyle, this);
    }
    set style(value: PathStyle) {
        $.utils.copyFrom(value, $.utils.getPointer(0, this));
    }
    _adoptVerbs(value: $.Orphan<$.Data>): void {
        $.utils.adopt(value, $.utils.getPointer(1, this));
    }
    _disownVerbs(): $.Orphan<$.Data> {
        return $.utils.disown(this.verbs);
    }
    get verbs(): $.Data {
        return $.utils.getData(1, this);
    }
    _hasVerbs(): boolean {
        return !$.utils.isNull($.utils.getPointer(1, this));
    }
    _initVerbs(length: number): $.Data {
        return $.utils.initData(1, length, this);
    }
    set verbs(value: $.Data) {
        $.utils.copyFrom(value, $.utils.getPointer(1, this));
    }
    _adoptCoords(value: $.Orphan<$.List<number>>): void {
        $.utils.adopt(value, $.utils.getPointer(2, this));
    }
    _disownCoords(): $.Orphan<$.List<number>> {
        return $.utils.disown(this.coords);
    }
    get coords(): $.List<number> {
        return $.utils.getList(2, $.Float32List, this);
    }
    _hasCoords(): boolean {
        return !$.utils.isNull($.utils.getPointer(2, this));
    }
    _initCoords(length: number): $.List<number> {
        return $.utils.initList(2, $.Float32List, length, this);
    }
    set coords(value: $.List<number>) {
        $.utils.copyFrom(value, $.utils.getPointer(2, this));
    }
    toString(): string { return "Path_" + super.toString(); }
}
export const Element_Which = {
    PATH: 0,
    CLIPPED: 1,
    TEXT: 2,
    BITMAP: 3,
    LAYER: 4
} as const;
export type Element_Which = (typeof Element_Which)[keyof typeof Element_Which];
export class Element extends $.Struct {
    static readonly PATH = Element_Which.PATH;
    static readonly CLIPPED = Element_Which.CLIPPED;
    static readonly TEXT = Element_Which.TEXT;
    static readonly BITMAP = Element_Which.BITMAP;
    static readonly LAYER = Element_Which.LAYER;
    static readonly _capnp = {
        displayName: "Element",
        id: "d733c7988e4f56d4",
        size: new $.ObjectSize(8, 1),
    };
    _adoptPath(value: $.Orphan<Path>): void {
        $.utils.setUint16(0, 0, this);
        $.utils.adopt(value, $.utils.getPointer(0, this));
    }
    _disownPath(): $.Orphan<Path> {
        return $.utils.disown(this.path);
    }
    get path(): Path {
        $.utils.testWhich("path", $.utils.getUint16(0, this), 0, this);
        return $.utils.getStruct(0, Path, this);
    }
    _hasPath(): boolean {
        return !$.utils.isNull($.utils.getPointer(0, this));
    }
    _initPath(): Path {
        $.utils.setUint16(0, 0, this);
        return $.utils.initStructAt(0, Path, this);
    }
    get _isPath(): boolean {
        return $.utils.getUint16(0, this) === 0;
    }
    set path(value: Path) {
        $.utils.setUint16(0, 0, this);
        $.utils.copyFrom(value, $.utils.getPointer(0, this));
    }
    _adoptClipped(value: $.Orphan<Clipped>): void {
        $.utils.setUint16(0, 1, this);
        $.utils.adopt(value, $.utils.getPointer(0, this));
    }
    _disownClipped(): $.Orphan<Clipped> {
        return $.utils.disown(this.clipped);
    }
    get clipped(): Clipped {
        $.utils.testWhich("clipped", $.utils.getUint16(0, this), 1, this);
        return $.utils.getStruct(0, Clipped, this);
    }
    _hasClipped(): boolean {
        return !$.utils.isNull($.utils.getPointer(0, this));
    }
    _initClipped(): Clipped {
        $.utils.setUint16(0, 1, this);
        return $.utils.initStructAt(0, Clipped, this);
    }
    get _isClipped(): boolean {
        return $.utils.getUint16(0, this) === 1;
    }
    set clipped(value: Clipped) {
        $.utils.setUint16(0, 1, this);
        $.utils.copyFrom(value, $.utils.getPointer(0, this));
    }
    _adoptText(value: $.Orphan<TextNode>): void {
        $.utils.setUint16(0, 2, this);
        $.utils.adopt(value, $.utils.getPointer(0, this));
    }
    _disownText(): $.Orphan<TextNode> {
        return $.utils.disown(this.text);
    }
    get text(): TextNode {
        $.utils.testWhich("text", $.utils.getUint16(0, this), 2, this);
        return $.utils.getStruct(0, TextNode, this);
    }
    _hasText(): boolean {
        return !$.utils.isNull($.utils.getPointer(0, this));
    }
    _initText(): TextNode {
        $.utils.setUint16(0, 2, this);
        return $.utils.initStructAt(0, TextNode, this);
    }
    get _isText(): boolean {
        return $.utils.getUint16(0, this) === 2;
    }
    set text(value: TextNode) {
        $.utils.setUint16(0, 2, this);
        $.utils.copyFrom(value, $.utils.getPointer(0, this));
    }
    _adoptBitmap(value: $.Orphan<Bitmap>): void {
        $.utils.setUint16(0, 3, this);
        $.utils.adopt(value, $.utils.getPointer(0, this));
    }
    _disownBitmap(): $.Orphan<Bitmap> {
        return $.utils.disown(this.bitmap);
    }
    get bitmap(): Bitmap {
        $.utils.testWhich("bitmap", $.utils.getUint16(0, this), 3, this);
        return $.utils.getStruct(0, Bitmap, this);
    }
    _hasBitmap(): boolean {
        return !$.utils.isNull($.utils.getPointer(0, this));
    }
    _initBitmap(): Bitmap {
        $.utils.setUint16(0, 3, this);
        return $.utils.initStructAt(0, Bitmap, this);
    }
    get _isBitmap(): boolean {
        return $.utils.getUint16(0, this) === 3;
    }
    set bitmap(value: Bitmap) {
        $.utils.setUint16(0, 3, this);
        $.utils.copyFrom(value, $.utils.getPointer(0, this));
    }
    _adoptLayer(value: $.Orphan<Layer>): void {
        $.utils.setUint16(0, 4, this);
        $.utils.adopt(value, $.utils.getPointer(0, this));
    }
    _disownLayer(): $.Orphan<Layer> {
        return $.utils.disown(this.layer);
    }
    get layer(): Layer {
        $.utils.testWhich("layer", $.utils.getUint16(0, this), 4, this);
        return $.utils.getStruct(0, Layer, this);
    }
    _hasLayer(): boolean {
        return !$.utils.isNull($.utils.getPointer(0, this));
    }
    _initLayer(): Layer {
        $.utils.setUint16(0, 4, this);
        return $.utils.initStructAt(0, Layer, this);
    }
    get _isLayer(): boolean {
        return $.utils.getUint16(0, this) === 4;
    }
    set layer(value: Layer) {
        $.utils.setUint16(0, 4, this);
        $.utils.copyFrom(value, $.utils.getPointer(0, this));
    }
    toString(): string { return "Element_" + super.toString(); }
    which(): Element_Which {
        return $.utils.getUint16(0, this) as Element_Which;
    }
}
export class Clipped extends $.Struct {
    static readonly _capnp = {
        displayName: "Clipped",
        id: "f904ed8669201e65",
        size: new $.ObjectSize(0, 2),
    };
    static _Elements: $.ListCtor<Element>;
    _adoptClip(value: $.Orphan<ClipPath>): void {
        $.utils.adopt(value, $.utils.getPointer(0, this));
    }
    _disownClip(): $.Orphan<ClipPath> {
        return $.utils.disown(this.clip);
    }
    get clip(): ClipPath {
        return $.utils.getStruct(0, ClipPath, this);
    }
    _hasClip(): boolean {
        return !$.utils.isNull($.utils.getPointer(0, this));
    }
    _initClip(): ClipPath {
        return $.utils.initStructAt(0, ClipPath, this);
    }
    set clip(value: ClipPath) {
        $.utils.copyFrom(value, $.utils.getPointer(0, this));
    }
    _adoptElements(value: $.Orphan<$.List<Element>>): void {
        $.utils.adopt(value, $.utils.getPointer(1, this));
    }
    _disownElements(): $.Orphan<$.List<Element>> {
        return $.utils.disown(this.elements);
    }
    get elements(): $.List<Element> {
        return $.utils.getList(1, Clipped._Elements, this);
    }
    _hasElements(): boolean {
        return !$.utils.isNull($.utils.getPointer(1, this));
    }
    _initElements(length: number): $.List<Element> {
        return $.utils.initList(1, Clipped._Elements, length, this);
    }
    set elements(value: $.List<Element>) {
        $.utils.copyFrom(value, $.utils.getPointer(1, this));
    }
    toString(): string { return "Clipped_" + super.toString(); }
}
export class Layer extends $.Struct {
    static readonly _capnp = {
        displayName: "Layer",
        id: "ef8b00858e36bb2a",
        size: new $.ObjectSize(8, 1),
        defaultOpacity: $.getFloat32Mask(1)
    };
    static _Elements: $.ListCtor<Element>;
    _adoptElements(value: $.Orphan<$.List<Element>>): void {
        $.utils.adopt(value, $.utils.getPointer(0, this));
    }
    _disownElements(): $.Orphan<$.List<Element>> {
        return $.utils.disown(this.elements);
    }
    get elements(): $.List<Element> {
        return $.utils.getList(0, Layer._Elements, this);
    }
    _hasElements(): boolean {
        return !$.utils.isNull($.utils.getPointer(0, this));
    }
    _initElements(length: number): $.List<Element> {
        return $.utils.initList(0, Layer._Elements, length, this);
    }
    set elements(value: $.List<Element>) {
        $.utils.copyFrom(value, $.utils.getPointer(0, this));
    }
    get opacity(): number {
        return $.utils.getFloat32(0, this, Layer._capnp.defaultOpacity);
    }
    set opacity(value: number) {
        $.utils.setFloat32(0, value, this, Layer._capnp.defaultOpacity);
    }
    toString(): string { return "Layer_" + super.toString(); }
}
export class Scene extends $.Struct {
    static readonly _capnp = {
        displayName: "Scene",
        id: "c942c45e95ae3bb7",
        size: new $.ObjectSize(8, 1),
    };
    static _Elements: $.ListCtor<Element>;
    get width(): number {
        return $.utils.getFloat32(0, this);
    }
    set width(value: number) {
        $.utils.setFloat32(0, value, this);
    }
    get height(): number {
        return $.utils.getFloat32(4, this);
    }
    set height(value: number) {
        $.utils.setFloat32(4, value, this);
    }
    _adoptElements(value: $.Orphan<$.List<Element>>): void {
        $.utils.adopt(value, $.utils.getPointer(0, this));
    }
    _disownElements(): $.Orphan<$.List<Element>> {
        return $.utils.disown(this.elements);
    }
    get elements(): $.List<Element> {
        return $.utils.getList(0, Scene._Elements, this);
    }
    _hasElements(): boolean {
        return !$.utils.isNull($.utils.getPointer(0, this));
    }
    _initElements(length: number): $.List<Element> {
        return $.utils.initList(0, Scene._Elements, length, this);
    }
    set elements(value: $.List<Element>) {
        $.utils.copyFrom(value, $.utils.getPointer(0, this));
    }
    toString(): string { return "Scene_" + super.toString(); }
}
LinearGradient._Stops = $.CompositeList(Stop);
RadialGradient._Stops = $.CompositeList(Stop);
Clipped._Elements = $.CompositeList(Element);
Layer._Elements = $.CompositeList(Element);
Scene._Elements = $.CompositeList(Element);
